name: Manage Cloud SQL Instances

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main

env:
  START_CRON: '0 7 * * 1-5'
  PAUSE_CRON: '0 20 * * 1-5'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine Action
        id: determine_action
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            action=$(if [ "${{ github.event.schedule }}" == "${{ env.START_CRON }}" ]; then echo "start"; else echo "stop"; fi)
          elif [ "${{ github.event_name }}" == "push" ]; then
            action="start"  # Default action for push event to main branch
          else
            action="stop"   # Default action if event is neither schedule nor push
          fi
          echo "::set-output name=action::$action"

      - name: Manage Cloud SQL Instance
        uses: ./.github/workflows/reusable-cloudsql-workflow.yaml
        with:
          action: ${{ steps.determine_action.outputs.action }}
        env:
          GCP_WORKLOAD_IDENTITY_PROVIDER_NAME: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          GCP_WORKLOAD_IDENTITY_SA_EMAIL: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
